<h1>Dictionary</h1>

In [110]:
#Dictionary Making 
dict_ = {"one":"menna", "two":"mostafa", "one":"mariam", "three":[1,2,3]}
print(type(dict_))
print(dict_)

<class 'dict'>
{'one': 'mariam', 'two': 'mostafa', 'three': [1, 2, 3]}


In [111]:
#Accessing dictionary
print(dict_["one"])
print(dict_.get("two"))
      
#Getting all values 
print(dict_.values())
for value in dict_.values():
    print("Value: " , value)

#Putting them in a list 
val_list = list(dict_.values())
print(type(val_list) ," : ",val_list)

#Getting all keys
print(dict_.keys())
for key in dict_.keys():
    print("Key: " , key)

#Putting them in a list 
key_list = list(dict_.keys())
print(type(key_list), " : ", key_list)

#Getting key with value
print(dict_.items())
for key,value in dict_.items():
    print("Key : " , key ,"," ," Value : " , value)

key_val_list = list(dict_.items())
print(type(key_val_list), " : " , key_val_list)

mariam
mostafa
dict_values(['mariam', 'mostafa', [1, 2, 3]])
Value:  mariam
Value:  mostafa
Value:  [1, 2, 3]
<class 'list'>  :  ['mariam', 'mostafa', [1, 2, 3]]
dict_keys(['one', 'two', 'three'])
Key:  one
Key:  two
Key:  three
<class 'list'>  :  ['one', 'two', 'three']
dict_items([('one', 'mariam'), ('two', 'mostafa'), ('three', [1, 2, 3])])
Key :  one ,  Value :  mariam
Key :  two ,  Value :  mostafa
Key :  three ,  Value :  [1, 2, 3]
<class 'list'>  :  [('one', 'mariam'), ('two', 'mostafa'), ('three', [1, 2, 3])]


In [112]:
#Adding
dict_.update({"four" : "omnia"})
dict_.update({5 : "islam"}) 
dict_.update({"six" : "nadeen"})
dict_.update({"seven" : "yara"})
print("Updating : " , dict_)

#Editing & Deleting
dict_["three"][1] = "edit"
print("Editing : " , dict_)

dict_.popitem()
print("Delete last item : " , dict_)

del dict_["three"]
dict_.pop("four")
print("Delete : " , dict_)

for key in list(dict_.keys()):
    if key == 5:
        del dict_[5]
    if key == "six":
        dict_[key] = "updated"

print(dict_)

Updating :  {'one': 'mariam', 'two': 'mostafa', 'three': [1, 2, 3], 'four': 'omnia', 5: 'islam', 'six': 'nadeen', 'seven': 'yara'}
Editing :  {'one': 'mariam', 'two': 'mostafa', 'three': [1, 'edit', 3], 'four': 'omnia', 5: 'islam', 'six': 'nadeen', 'seven': 'yara'}
Delete last item :  {'one': 'mariam', 'two': 'mostafa', 'three': [1, 'edit', 3], 'four': 'omnia', 5: 'islam', 'six': 'nadeen'}
Delete :  {'one': 'mariam', 'two': 'mostafa', 5: 'islam', 'six': 'nadeen'}
{'one': 'mariam', 'two': 'mostafa', 'six': 'updated'}


In [113]:
#Dictionary copy
dict_copy = dict_.copy()
print(dict_copy)

#Set Default
x = dict_copy.setdefault("two","default")
print(x)
dict_copy.setdefault("seven","default")
print("dict copy : ", dict_copy)

#Forming new DIC with VAL
keys = (1,2,3)
values = 2
new_dict = dict.fromkeys(keys,values)

print("New Dict : " , new_dict)

#Dictionary Length
print("Dict leng : " , len(new_dict))

#Clearing original dict
dict_.clear()
print("Original dict : " , dict_)
print("Copy dict : " , dict_copy)

{'one': 'mariam', 'two': 'mostafa', 'six': 'updated'}
mostafa
dict copy :  {'one': 'mariam', 'two': 'mostafa', 'six': 'updated', 'seven': 'default'}
New Dict :  {1: 2, 2: 2, 3: 2}
Dict leng :  3
Original dict :  {}
Copy dict :  {'one': 'mariam', 'two': 'mostafa', 'six': 'updated', 'seven': 'default'}


In [117]:
#finding a pair of key val their summation = 4
found = any(key + val == 4 for key,val in new_dict.items())
print(found)

#While loop with dictionary
list_k = list(dict_copy)
i = 0
while i < len(list_k):
    print(list_k[i] ,  dict_copy[list_k[i]])
    i += 1


True
one mariam
two mostafa
six updated
seven default


In [118]:
#any function 

'''
any[condition for x in list]

def any(iterable):
    for element in iterable:
        if element:
            return True
    return False
'''

'\nany[condition for x in list]\n\ndef any(iterable):\n    for element in iterable:\n        if element:\n            return True\n    return False\n'

<h1>DataFrame</h1>

In [78]:
import pandas as pd
#Converting a dictionary to dataframe
dictionary = {"col1": [1,2,3], "col2": ["row1","row2","row3"]}
df_conv = pd.DataFrame(dictionary)
print(df_conv)
print(type(df_conv))

   col1  col2
0     1  row1
1     2  row2
2     3  row3
<class 'pandas.core.frame.DataFrame'>


In [79]:
#Reading from a csv
df_csv = pd.read_csv('C:/Users/Dell/Desktop/GS/Task2/Dataset.csv')
df_csv

ID Marital Status Gender  Income  Children            Education  \
0     12496              M      F   40000         1            Bachelors   
1     24107              M      M   30000         3      Partial College   
2     14177              M      M   80000         5      Partial College   
3     24381              S      M   70000         0            Bachelors   
4     25597              S      M   30000         0            Bachelors   
...     ...            ...    ...     ...       ...                  ...   
1021  16466              S      F   20000         0  Partial High School   
1022  19273              M      F   20000         2      Partial College   
1023  22400              M      M   10000         0      Partial College   
1024  20942              S      F   20000         0          High School   
1025  18484              S      M   80000         2          High School   

          Occupation Home Owner  Cars Commute Distance   Region  Age  \
0     Skilled Manual        Yes   0.0        0-1 Miles   Europe   42   
1           Clerical        Yes   1.0        0-1 Miles   Europe   43   
2       Professional         No   2.0        2-5 Miles   Europe   60   
3       Professional        Yes   1.0       5-10 Miles  Pacific   41   
4           Clerical         No   0.0        0-1 Miles   Europe   36   
...              ...        ...   ...              ...      ...  ...   
1021          Manual         No   2.0        0-1 Miles   Europe   32   
1022          Manual        Yes   0.0        0-1 Miles   Europe   63   
1023          Manual         No   1.0        0-1 Miles  Pacific   26   
1024             NaN         No   1.0       5-10 Miles   Europe   31   
1025  Skilled Manual         No   2.0        1-2 Miles  Pacific   50   

     Purchased Bike  
0                No  
1                No  
2                No  
3               Yes  
4               Yes  
...             ...  
1021            Yes  
1022             No  
1023            Yes  
1024             No  
1025            Yes  

[1026 rows x 13 columns]

In [80]:
#show dataframe index, columns
print("index: ", df_csv.index)
print("cols: ", df_csv.columns)

#show dataframe data types
print("Cols Datatypes:\n", df_csv.dtypes)

index:  RangeIndex(start=0, stop=1026, step=1)
cols:  Index(['ID', 'Marital Status', 'Gender', 'Income', 'Children', 'Education',
       'Occupation', 'Home Owner', 'Cars', 'Commute Distance', 'Region', 'Age',
       'Purchased Bike'],
      dtype='object')
Cols Datatypes:
 ID                    int64
Marital Status       object
Gender               object
Income                int64
Children              int64
Education            object
Occupation           object
Home Owner           object
Cars                float64
Commute Distance     object
Region               object
Age                   int64
Purchased Bike       object
dtype: object


In [81]:
#Getting data info WHY ? to check the null count of each column and the data type of each column 
#Better than dtypes because we got more info about the data
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1026 entries, 0 to 1025
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   ID                1026 non-null   int64  
 1   Marital Status    1026 non-null   object 
 2   Gender            1026 non-null   object 
 3   Income            1026 non-null   int64  
 4   Children          1026 non-null   int64  
 5   Education         1026 non-null   object 
 6   Occupation        1024 non-null   object 
 7   Home Owner        1026 non-null   object 
 8   Cars              1024 non-null   float64
 9   Commute Distance  1026 non-null   object 
 10  Region            1025 non-null   object 
 11  Age               1026 non-null   int64  
 12  Purchased Bike    1026 non-null   object 
dtypes: float64(1), int64(4), object(8)
memory usage: 104.3+ KB


In [82]:
#Checking the data by looking at the first 10 rows and last 5 rows
df_csv.head(10)

ID Marital Status Gender  Income  Children            Education  \
0  12496              M      F   40000         1            Bachelors   
1  24107              M      M   30000         3      Partial College   
2  14177              M      M   80000         5      Partial College   
3  24381              S      M   70000         0            Bachelors   
4  25597              S      M   30000         0            Bachelors   
5  13507              M      F   10000         2      Partial College   
6  27974              S      M  160000         2          High School   
7  19364              M      M   40000         1            Bachelors   
8  22155              M      M   20000         2  Partial High School   
9  19280              M      M  120000         2      Partial College   

       Occupation Home Owner  Cars Commute Distance   Region  Age  \
0  Skilled Manual        Yes   0.0        0-1 Miles   Europe   42   
1        Clerical        Yes   1.0        0-1 Miles   Europe   43   
2    Professional         No   2.0        2-5 Miles   Europe   60   
3    Professional        Yes   1.0       5-10 Miles  Pacific   41   
4        Clerical         No   0.0        0-1 Miles   Europe   36   
5          Manual        Yes   0.0        1-2 Miles   Europe   50   
6      Management        Yes   4.0        0-1 Miles  Pacific   33   
7  Skilled Manual        Yes   0.0        0-1 Miles   Europe   43   
8        Clerical        Yes   2.0       5-10 Miles  Pacific   58   
9          Manual        Yes   1.0        0-1 Miles   Europe   40   

  Purchased Bike  
0             No  
1             No  
2             No  
3            Yes  
4            Yes  
5             No  
6            Yes  
7            Yes  
8             No  
9            Yes

In [83]:
df_csv.tail()

ID Marital Status Gender  Income  Children            Education  \
1021  16466              S      F   20000         0  Partial High School   
1022  19273              M      F   20000         2      Partial College   
1023  22400              M      M   10000         0      Partial College   
1024  20942              S      F   20000         0          High School   
1025  18484              S      M   80000         2          High School   

          Occupation Home Owner  Cars Commute Distance   Region  Age  \
1021          Manual         No   2.0        0-1 Miles   Europe   32   
1022          Manual        Yes   0.0        0-1 Miles   Europe   63   
1023          Manual         No   1.0        0-1 Miles  Pacific   26   
1024             NaN         No   1.0       5-10 Miles   Europe   31   
1025  Skilled Manual         No   2.0        1-2 Miles  Pacific   50   

     Purchased Bike  
1021            Yes  
1022             No  
1023            Yes  
1024             No  
1025            Yes

In [84]:
#Check the dimension of the object (Series or Dataframe)
series = pd.Series([1,2,3,4])
print("series dimension : ", series.ndim)
print("Dataframe dimension : ", df_csv.ndim)
#Dataframe size & shape
print("Dataframe Size : ", df_csv.size)
print("Dataframe Shape(no. of rows & columns) : ", df_csv.shape) 
#Check if dataframe is empty
print("Dataframe emptniess : ", df_csv.empty)

series dimension :  1
Dataframe dimension :  2
Dataframe Size :  13338
Dataframe Shape(no. of rows & columns) :  (1026, 13)
Dataframe emptniess :  False


In [85]:
#Detecting missing values
df_csv.isna()

ID  Marital Status  Gender  Income  Children  Education  Occupation  \
0     False           False   False   False     False      False       False   
1     False           False   False   False     False      False       False   
2     False           False   False   False     False      False       False   
3     False           False   False   False     False      False       False   
4     False           False   False   False     False      False       False   
...     ...             ...     ...     ...       ...        ...         ...   
1021  False           False   False   False     False      False       False   
1022  False           False   False   False     False      False       False   
1023  False           False   False   False     False      False       False   
1024  False           False   False   False     False      False        True   
1025  False           False   False   False     False      False       False   

      Home Owner   Cars  Commute Distance  Region    Age  Purchased Bike  
0          False  False             False   False  False           False  
1          False  False             False   False  False           False  
2          False  False             False   False  False           False  
3          False  False             False   False  False           False  
4          False  False             False   False  False           False  
...          ...    ...               ...     ...    ...             ...  
1021       False  False             False   False  False           False  
1022       False  False             False   False  False           False  
1023       False  False             False   False  False           False  
1024       False  False             False   False  False           False  
1025       False  False             False   False  False           False  

[1026 rows x 13 columns]

In [86]:
#Filling some missing values, Indexing 0 as mode returns series of of items
df_csv["Occupation"].fillna(df_csv["Occupation"].mode()[0], inplace = True)
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1026 entries, 0 to 1025
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   ID                1026 non-null   int64  
 1   Marital Status    1026 non-null   object 
 2   Gender            1026 non-null   object 
 3   Income            1026 non-null   int64  
 4   Children          1026 non-null   int64  
 5   Education         1026 non-null   object 
 6   Occupation        1026 non-null   object 
 7   Home Owner        1026 non-null   object 
 8   Cars              1024 non-null   float64
 9   Commute Distance  1026 non-null   object 
 10  Region            1025 non-null   object 
 11  Age               1026 non-null   int64  
 12  Purchased Bike    1026 non-null   object 
dtypes: float64(1), int64(4), object(8)
memory usage: 104.3+ KB


C:\Users\Dell\AppData\Local\Temp\ipykernel_8368\3640194452.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_csv["Occupation"].fillna(df_csv["Occupation"].mode()[0], inplace = True)


In [87]:
#Drop other rows with na values
df_csv.dropna(axis=0, inplace = True)
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1023 entries, 0 to 1025
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   ID                1023 non-null   int64  
 1   Marital Status    1023 non-null   object 
 2   Gender            1023 non-null   object 
 3   Income            1023 non-null   int64  
 4   Children          1023 non-null   int64  
 5   Education         1023 non-null   object 
 6   Occupation        1023 non-null   object 
 7   Home Owner        1023 non-null   object 
 8   Cars              1023 non-null   float64
 9   Commute Distance  1023 non-null   object 
 10  Region            1023 non-null   object 
 11  Age               1023 non-null   int64  
 12  Purchased Bike    1023 non-null   object 
dtypes: float64(1), int64(4), object(8)
memory usage: 111.9+ KB


In [88]:
#Copying dataframe and diff between deep and shallow
#Using loc to modify the data
deep_df = df_conv.copy(deep=True)
shallow_df = df_conv.copy(deep=False)
print("Deep:\n" ,deep_df)
print("shallow:\n", shallow_df)
deep_df.loc[0,"col1"] = 5
print("Changing In Deep:\n")
print("Deep:\n" , deep_df)
print("Shallow:\n", shallow_df)
print("Original:\n", df_conv)
shallow_df.loc[0,"col2"] = "Changed"
print("Changing In Shallow:\n")
print("Deep:\n" , deep_df)
print("Shallow:\n", shallow_df)
print("Original:\n", df_conv)

Deep:
    col1  col2
0     1  row1
1     2  row2
2     3  row3
shallow:
    col1  col2
0     1  row1
1     2  row2
2     3  row3
Changing In Deep:

Deep:
    col1  col2
0     5  row1
1     2  row2
2     3  row3
Shallow:
    col1  col2
0     1  row1
1     2  row2
2     3  row3
Original:
    col1  col2
0     1  row1
1     2  row2
2     3  row3
Changing In Shallow:

Deep:
    col1  col2
0     5  row1
1     2  row2
2     3  row3
Shallow:
    col1     col2
0     1  Changed
1     2     row2
2     3     row3
Original:
    col1     col2
0     1  Changed
1     2     row2
2     3     row3


In [89]:
#Using iloc to access certain rows the data
print(df_conv.iloc[1:3])
print("\n")
#Accesing certain columns
print(df_csv.iloc[0:,1:3])

   col1  col2
1     2  row2
2     3  row3


     Marital Status Gender
0                 M      F
1                 M      M
2                 M      M
3                 S      M
4                 S      M
...             ...    ...
1021              S      F
1022              M      F
1023              M      M
1024              S      F
1025              S      M

[1023 rows x 2 columns]


In [90]:
#Inserting new column 
df_conv.insert(1,"new_col", value=["a","b","c"])
print(df_conv)
#Inserting new column with a duplicate name
df_conv.insert(2,"new_col", value=["a","b","c"], allow_duplicates=True)
print(df_conv)

   col1 new_col     col2
0     1       a  Changed
1     2       b     row2
2     3       c     row3
   col1 new_col new_col     col2
0     1       a       a  Changed
1     2       b       b     row2
2     3       c       c     row3


In [91]:
#Dropping a column
df_csv.drop("ID",axis=1,inplace=True)

In [92]:
df_csv

Marital Status Gender  Income  Children            Education  \
0                 M      F   40000         1            Bachelors   
1                 M      M   30000         3      Partial College   
2                 M      M   80000         5      Partial College   
3                 S      M   70000         0            Bachelors   
4                 S      M   30000         0            Bachelors   
...             ...    ...     ...       ...                  ...   
1021              S      F   20000         0  Partial High School   
1022              M      F   20000         2      Partial College   
1023              M      M   10000         0      Partial College   
1024              S      F   20000         0          High School   
1025              S      M   80000         2          High School   

          Occupation Home Owner  Cars Commute Distance   Region  Age  \
0     Skilled Manual        Yes   0.0        0-1 Miles   Europe   42   
1           Clerical        Yes   1.0        0-1 Miles   Europe   43   
2       Professional         No   2.0        2-5 Miles   Europe   60   
3       Professional        Yes   1.0       5-10 Miles  Pacific   41   
4           Clerical         No   0.0        0-1 Miles   Europe   36   
...              ...        ...   ...              ...      ...  ...   
1021          Manual         No   2.0        0-1 Miles   Europe   32   
1022          Manual        Yes   0.0        0-1 Miles   Europe   63   
1023          Manual         No   1.0        0-1 Miles  Pacific   26   
1024    Professional         No   1.0       5-10 Miles   Europe   31   
1025  Skilled Manual         No   2.0        1-2 Miles  Pacific   50   

     Purchased Bike  
0                No  
1                No  
2                No  
3               Yes  
4               Yes  
...             ...  
1021            Yes  
1022             No  
1023            Yes  
1024             No  
1025            Yes  

[1023 rows x 12 columns]

In [101]:
import numpy as np
#Grouping by a certain column 
print(df_csv.groupby(by="Gender").mean(numeric_only=True).apply(np.ceil))
#Grouping by multiple columns
print(df_csv.groupby(by=["Gender","Purchased Bike"]).mean(numeric_only=True).apply(np.ceil))
#Grouping With multiple agg. func. for certain col.
print(df_csv.groupby(by=["Gender","Purchased Bike"]).agg({"Purchased Bike": ["count"], "Income":["mean","median","max","min"]}))

         Income  Children  Cars   Age
Gender                               
F       54240.0       2.0   2.0  45.0
M       58050.0       2.0   2.0  45.0
                        Income  Children  Cars   Age
Gender Purchased Bike                               
F      No              53269.0       3.0   2.0  46.0
       Yes             55268.0       2.0   2.0  43.0
M      No              56508.0       3.0   2.0  46.0
       Yes             59722.0       2.0   2.0  44.0
                      Purchased Bike        Income                        
                               count          mean   median     max    min
Gender Purchased Bike                                                     
F      No                        257  53268.482490  50000.0  130000  10000
       Yes                       243  55267.489712  60000.0  170000  10000
M      No                        272  56507.352941  60000.0  170000  10000
       Yes                       251  59721.115538  60000.0  160000  10000


In [119]:
#Merging two tables 
df1 = pd.DataFrame({'name': ['mariam', 'mostafa', 'omnia'],
                    'no': [1, 2, 3],
                      'diff': ["a","b","c"]})
df2 = pd.DataFrame({'name': ['nadeen', 'mostafa', 'omnia','yara'],
                    'no': [1, 2, 3,6],
                      'different' : ["d","e","f","g"]})
print(df1)
print(df2)
#inner
print("\nInner:")
print(df1.merge(df2,on="name"))
#left
print("\nLeft:")
print(df1.merge(df2,how="left",on="no"))
#right
print("\nRight:")
print(df1.merge(df2,how="right"))
#cross
print("\nCross:")
print(df1.merge(df2,how="cross"))

      name  no diff
0   mariam   1    a
1  mostafa   2    b
2    omnia   3    c
      name  no different
0   nadeen   1         d
1  mostafa   2         e
2    omnia   3         f
3     yara   6         g

Inner:
      name  no_x diff  no_y different
0  mostafa     2    b     2         e
1    omnia     3    c     3         f

Left:
    name_x  no diff   name_y different
0   mariam   1    a   nadeen         d
1  mostafa   2    b  mostafa         e
2    omnia   3    c    omnia         f

Right:
      name  no diff different
0   nadeen   1  NaN         d
1  mostafa   2    b         e
2    omnia   3    c         f
3     yara   6  NaN         g

Cross:
     name_x  no_x diff   name_y  no_y different
0    mariam     1    a   nadeen     1         d
1    mariam     1    a  mostafa     2         e
2    mariam     1    a    omnia     3         f
3    mariam     1    a     yara     6         g
4   mostafa     2    b   nadeen     1         d
5   mostafa     2    b  mostafa     2         e
6   most

In [150]:
#Mathematical fn
print("Max : ", df_csv["Income"].max())
print("Min : ", df_csv["Income"].min())
print("Average : ", df_csv["Income"].mean())
print("Median : ", df_csv["Income"].median())
print("Mode : ", df_csv["Education"].mode())
print("Count : ", df_csv[df_csv["Education"] == "Bachelors"].count().iloc[0])
print("Sum : ", df_csv["Income"].sum())

Max :  170000
Min :  10000
Average :  56187.683284457475
Median :  60000.0
Mode :  0    Bachelors
Name: Education, dtype: object
Count :  309
Sum :  57480000


In [157]:
#Getting stat info about it 
#But doing it individualy as above better when calculating for certain condition as above
df_csv.describe()

Income     Children         Cars          Age
count    1023.000000  1023.000000  1023.000000  1023.000000
mean    56187.683284     1.894428     1.436950    44.159335
std     31298.261595     1.625566     1.125963    11.355104
min     10000.000000     0.000000     0.000000    25.000000
25%     30000.000000     0.000000     1.000000    35.000000
50%     60000.000000     2.000000     1.000000    43.000000
75%     70000.000000     3.000000     2.000000    52.000000
max    170000.000000     5.000000     4.000000    89.000000

In [153]:
#Counting unique Values
df_csv.nunique()

Marital Status       2
Gender               2
Income              16
Children             6
Education            5
Occupation           5
Home Owner           2
Cars                 5
Commute Distance     5
Region               3
Age                 53
Purchased Bike       2
dtype: int64

In [156]:
#Dropping Duplicates
df_csv.drop_duplicates()
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1023 entries, 0 to 1025
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Marital Status    1023 non-null   object 
 1   Gender            1023 non-null   object 
 2   Income            1023 non-null   int64  
 3   Children          1023 non-null   int64  
 4   Education         1023 non-null   object 
 5   Occupation        1023 non-null   object 
 6   Home Owner        1023 non-null   object 
 7   Cars              1023 non-null   float64
 8   Commute Distance  1023 non-null   object 
 9   Region            1023 non-null   object 
 10  Age               1023 non-null   int64  
 11  Purchased Bike    1023 non-null   object 
dtypes: float64(1), int64(3), object(8)
memory usage: 103.9+ KB


<h1>NumPy</h1>

In [158]:
import numpy as np

In [184]:
#Array Creation 
#From python sequence
arr = [1,2,3,4]
type(arr)
np_arr = np.array(arr,ndmin=2)
print(type(np_arr))
print(np_arr)
#1D array creation
print("Arrange:")
print(np.arange(1,10))
print(np.arange(1,10,2))
#2D array creation 
#Using eye
print("Eye:")
print("##")
print(np.eye(2))
print("##")
print(np.eye(3,4))
print("##")
print(np.eye(3,4,-1))
#2d one array
print("ones:")
print("##")
print(np.ones(2))
print("##")
print(np.ones((3,3)))
#2d zero array
print("zeros:")
print("##")
print(np.zeros(2))
print("##")
print(np.zeros((3,3)))

<class 'numpy.ndarray'>
[[1 2 3 4]]
Arrange:
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
Eye:
##
[[1. 0.]
 [0. 1.]]
##
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
##
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
ones:
##
[1. 1.]
##
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
zeros:
##
[0. 0.]
##
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [208]:
#Copying
print("Copying: ")
arr_ = np.arange(1,10)
arr_copy = arr_.copy()
print(arr_)
print(arr_copy)
arr_copy[1] = 55
print(arr_)
print(arr_copy)
#Joining arr
print("Joining arrays: ")
arr1 = np.eye(4)
arr2 = np.ones((2,4))
print(np.block([[arr1],
              [arr2]]))
#Shaping and sizing
print("array shape: ", np.shape(arr1))
print("array size: ", np.size(arr1)) 

#reshaping
arr_reshaped = np.reshape(arr1,(2,8))
print(arr_reshaped)
print("array shape: ", np.shape(arr_reshaped))
print("array shape: ", np.size(arr_reshaped))

#non-zero searching 
print(np.nonzero(arr_reshaped))

Copying: 
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[ 1 55  3  4  5  6  7  8  9]
Joining arrays: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
array shape:  (4, 4)
array size:  16
[[1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]]
array shape:  (2, 8)
array shape:  16
(array([0, 0, 1, 1]), array([0, 5, 2, 7]))


In [240]:
#ufunc
#Arithmatic
arr_1 = np.ones(2) * 2
arr_2 = np.zeros(2) 
print("sum : ", np.add(arr_1,arr_2))
print("sub : ", np.subtract(arr_2,arr_1))
print("multiply : ", np.multiply(arr_1,arr_2))
arr_2 += 4
print("divide : ", np.divide(arr_1,arr_2))
print("power : ", np.power(arr_1,arr_2))
#Trig
arr_angles = np.array([45, 60, 90])
print("sin: ", np.sin(arr_angles))
print("cos: ", np.cos(arr_angles))
print("tan: ", np.tan(arr_angles))
#Comparisons
#greater than 
print(arr_1)
print(arr_2)
print("arr1 Greater than or equal arr_2: ", np.greater_equal(arr_1,arr_2)) 
print("arr1 less than arr_2: ", np.less(arr_1,arr_2)) 
print("arr1 equal to arr_2: ", np.equal(arr_1,arr_2)) 

sum :  [2. 2.]
sub :  [-2. -2.]
multiply :  [0. 0.]
divide :  [0.5 0.5]
power :  [16. 16.]
sin:  [ 0.85090352 -0.30481062  0.89399666]
cos:  [ 0.52532199 -0.95241298 -0.44807362]
tan:  [ 1.61977519  0.32004039 -1.99520041]
[2. 2.]
[4. 4.]
arr1 Greater than or equal arr_2:  [False False]
arr1 less than arr_2:  [ True  True]
arr1 equal to arr_2:  [False False]


In [243]:
#Mathematical functions on the elements of the array itself
math_arr = np.array([1,2,3,4])
print("sum : " , np.sum(math_arr))
print("product : " , np.prod(math_arr))
print("cumulative sum : " , np.cumulative_sum(math_arr))
print("max : " , np.max(math_arr))
print("min : " , np.min(math_arr))

sum :  10
product :  24
cumulative sum :  [ 1  3  6 10]
max :  4
min :  1


In [247]:
#Dot Product
math_arr_1 = np.zeros(2) + 3
math_arr_2 = np.ones(2) + 2
print(np.linalg.multi_dot([math_arr_1,math_arr_2]))

18.0


In [251]:
#Get index of smallest value
min_arr = np.array([[2,2,1,4],
                     [0,1,2,3]])
print(min_arr)
print(np.argmin(min_arr))

[[2 2 1 4]
 [0 1 2 3]]
4
